In [1]:
from transformers import BertTokenizer
from modeling.character_bert import CharacterBertModel
from utils.character_cnn import CharacterIndexer

/Users/robertoesposito/tmp/charBert/character-bert/venv.nosync/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/robertoesposito/tmp/charBert/character-bert/venv.nosync/lib/python3.12/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(


In [13]:
# Example text
x = "Roberto Roberto Giulia Julia Michele Michael"

# Tokenize the text
tokenizer = BertTokenizer.from_pretrained("./pretrained-models/general_bert")
x = tokenizer.basic_tokenizer.tokenize(x)

xx = [["[CLS]", z, "[SEP]"] for z in x]

# # Add [CLS] and [SEP]
# x = ["[CLS]", *x, "[SEP]"]


# batch_ids = indexer.as_padded_tensor(xx)
# embeddings, _ = model(batch_ids)


embeddings = []
for x in xx:
    # Convert token sequence into character indices
    indexer = CharacterIndexer()
    batch = [x]  # This is a batch with a single token sequence x
    batch_ids = indexer.as_padded_tensor(batch)

    # model = CharacterBertModel.from_pretrained("./pretrained-models/general_bert/")
    model.eval()

    # Load some pre-trained CharacterBERT
    embeddings_for_batch, _ = model(batch_ids)
    embeddings_for_x = embeddings_for_batch[0]
    print(embeddings_for_x)

    embeddings.append(embeddings_for_x)

tensor([[-5.3723e-01,  3.3921e-01, -7.8173e-02,  ..., -3.3750e-01,
         -7.8714e-02,  3.0930e-01],
        [-4.3367e-01,  5.4027e-01, -2.3701e-03,  ..., -5.6598e-01,
         -1.0225e-01, -3.0638e-04],
        [-4.3764e-01,  5.3416e-01, -8.5225e-03,  ..., -4.8233e-01,
         -2.0777e-01, -3.0318e-02]], grad_fn=<SelectBackward0>)
tensor([[-5.3723e-01,  3.3921e-01, -7.8173e-02,  ..., -3.3750e-01,
         -7.8714e-02,  3.0930e-01],
        [-4.3367e-01,  5.4027e-01, -2.3701e-03,  ..., -5.6598e-01,
         -1.0225e-01, -3.0638e-04],
        [-4.3764e-01,  5.3416e-01, -8.5225e-03,  ..., -4.8233e-01,
         -2.0777e-01, -3.0318e-02]], grad_fn=<SelectBackward0>)
tensor([[-5.3723e-01,  3.3921e-01, -7.8173e-02,  ..., -3.3750e-01,
         -7.8714e-02,  3.0930e-01],
        [-4.3367e-01,  5.4027e-01, -2.3701e-03,  ..., -5.6598e-01,
         -1.0225e-01, -3.0638e-04],
        [-4.3764e-01,  5.3416e-01, -8.5225e-03,  ..., -4.8233e-01,
         -2.0777e-01, -3.0318e-02]], grad_fn=<SelectB

In [4]:
# x = "Roberto Roberto Giulia Julia Michele Michael"

def dist(x,y):
    return x.dot(y)/(x.norm()*y.norm())

def dist2(x,y):
    return (x-y).norm()

for i in range(len(embeddings)):
    for j in range(i+1,len(embeddings)):
        print(i,j,dist2(embeddings[i][1],embeddings[j][1]))

0 1 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
0 2 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
0 3 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
0 4 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
0 5 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
1 2 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
1 3 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
1 4 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
1 5 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
2 3 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
2 4 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
2 5 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
3 4 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
3 5 tensor(0., grad_fn=<LinalgVectorNormBackward0>)
4 5 tensor(0., grad_fn=<LinalgVectorNormBackward0>)


In [5]:
xx

[['[CLS]', 'roberto', '[SEP]'],
 ['[CLS]', 'roberto', '[SEP]'],
 ['[CLS]', 'giulia', '[SEP]'],
 ['[CLS]', 'julia', '[SEP]'],
 ['[CLS]', 'michele', '[SEP]'],
 ['[CLS]', 'michael', '[SEP]']]

In [6]:
embeddings

[tensor([[-0.1803,  0.6219,  0.1916,  ...,  0.2608, -0.6686,  0.3573],
         [ 0.0013,  0.3129,  0.3235,  ...,  0.3491, -0.8054,  0.7946],
         [ 0.0132,  0.3791,  0.4195,  ...,  0.3083, -0.7438,  0.7282]],
        grad_fn=<SelectBackward0>),
 tensor([[-0.1803,  0.6219,  0.1916,  ...,  0.2608, -0.6686,  0.3573],
         [ 0.0013,  0.3129,  0.3235,  ...,  0.3491, -0.8054,  0.7946],
         [ 0.0132,  0.3791,  0.4195,  ...,  0.3083, -0.7438,  0.7282]],
        grad_fn=<SelectBackward0>),
 tensor([[-0.1803,  0.6219,  0.1916,  ...,  0.2608, -0.6686,  0.3573],
         [ 0.0013,  0.3129,  0.3235,  ...,  0.3491, -0.8054,  0.7946],
         [ 0.0132,  0.3791,  0.4195,  ...,  0.3083, -0.7438,  0.7282]],
        grad_fn=<SelectBackward0>),
 tensor([[-0.1803,  0.6219,  0.1916,  ...,  0.2608, -0.6686,  0.3573],
         [ 0.0013,  0.3129,  0.3235,  ...,  0.3491, -0.8054,  0.7946],
         [ 0.0132,  0.3791,  0.4195,  ...,  0.3083, -0.7438,  0.7282]],
        grad_fn=<SelectBackward0>),
